version: '2'

services:
  postgresql:
    container_name: psql
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - './psql:/bitnami/postgresql'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
volumes:
  postgresql_data:
    driver: local
