# Generated by Django 3.1 on 2020-08-07 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminEventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='event_type',
            field=models.CharField(choices=[('PRESENCIAL', 'PRESENCIAL'), ('VIRTUAL', 'VIRTUAL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
