# Generated by Django 3.1 on 2020-08-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminEventos', '0002_auto_20200807_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='thumbnail',
            field=models.ImageField(upload_to='event_thumbnails'),
        ),
    ]
