# Generated by Django 3.1 on 2020-08-08 04:33

import AdminEventos.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AdminEventos', '0003_auto_20200808_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='thumbnail',
            field=models.ImageField(upload_to=AdminEventos.models.UploadToPathAndRename('event_thumbnails/')),
        ),
    ]
